/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type TalaDBNode = TalaDbNode
export declare class TalaDbNode {
  /** Open an in-memory database (useful for testing). */
  static openInMemory(): TalaDbNode
  /**
   * Open a file-backed database at the given path.
   *
   * Pass an optional JSON-serialised `TalaDbConfig` as `config_json` to
   * activate HTTP push sync. When `sync.enabled` is `true` and the
   * `sync-http` feature is compiled in, an `HttpSyncHook` is attached to
   * every collection returned by `collection()`.
   */
  static open(path: string, configJson?: string | undefined | null): TalaDbNode
  /**
   * Get a collection by name. If an HTTP sync hook is configured it is
   * automatically attached to the returned collection.
   */
  collection(name: string): CollectionNode
}
export declare class CollectionNode {
  /** Insert a document. Returns the ULID string id. */
  insert(doc: JsonValue): string
  /** Insert multiple documents. */
  insertMany(docs: Array<JsonValue>): Array<string>
  /** Find documents matching the filter. */
  find(filter: JsonValue): Array<JsonValue>
  /** Find a single document or return null. */
  findOne(filter: JsonValue): JsonValue | null
  /** Update the first matching document. */
  updateOne(filter: JsonValue, update: JsonValue): boolean
  /** Update all matching documents. */
  updateMany(filter: JsonValue, update: JsonValue): number
  /** Delete the first matching document. */
  deleteOne(filter: JsonValue): boolean
  /** Delete all matching documents. */
  deleteMany(filter: JsonValue): number
  /** Count documents matching the filter. */
  count(filter: JsonValue): number
  /** Create a secondary index on a field. */
  createIndex(field: string): void
  /** Drop a secondary index. */
  dropIndex(field: string): void
  /**
   * Create a vector index on `field`.
   *
   * - `metric` — optional: `"cosine"` (default), `"dot"`, or `"euclidean"`.
   * - `index_type` — optional: `"flat"` (default) or `"hnsw"`.
   * - `hnsw_m` — HNSW connectivity (default 16).
   * - `hnsw_ef_construction` — build quality (default 200).
   */
  createVectorIndex(field: string, dimensions: number, metric?: string | undefined | null, indexType?: string | undefined | null, hnswM?: number | undefined | null, hnswEfConstruction?: number | undefined | null): void
  /** Drop a vector index (and its HNSW graph if present). */
  dropVectorIndex(field: string): void
  /**
   * Rebuild the HNSW graph for a vector index from the current flat data.
   * No-op when the feature is disabled or the index is flat-only.
   */
  upgradeVectorIndex(field: string): void
  /**
   * Find the `top_k` nearest documents to `query`.
   *
   * `filter` — optional pre-filter in the same JSON object format as `find`.
   *
   * Returns an array of `{ document: {...}, score: number }` objects.
   */
  findNearest(field: string, query: Array<number>, topK: number, filter?: JsonValue | undefined | null): Array<JsonValue>
}
