/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type TalaDBNode = TalaDbNode
export declare class TalaDbNode {
  /** Open an in-memory database (useful for testing). */
  static openInMemory(): TalaDbNode
  /**
   * Open a file-backed database at the given path.
   *
   * Pass an optional JSON-serialised `TalaDbConfig` as `config_json` to
   * activate HTTP push sync. When `sync.enabled` is `true` and the
   * `sync-http` feature is compiled in, an `HttpSyncHook` is attached to
   * every collection returned by `collection()`.
   */
  static open(path: string, configJson?: string | undefined | null, passphrase?: string | undefined | null): TalaDbNode
  /**
   * Compact the underlying storage file, reclaiming space freed by deletes
   * and updates. Call during idle periods after large bulk deletes or
   * tombstone compaction. Returns the number of bytes reclaimed (may be 0).
   */
  compact(): void
  /**
   * Close the database, releasing the file handle and its lock.
   *
   * Subsequent calls on this object return an error. Collections obtained
   * before `close()` keep the underlying storage alive until they are
   * garbage-collected — drop them too to fully release the file.
   */
  close(): void
  /**
   * List user collection names (excludes reserved `_`-prefixed collections
   * such as the sync cursor store). Backs "sync all collections".
   */
  listCollectionNames(): Array<string>
  /**
   * Export changes to `collections` after `sinceMs` (exclusive) as a JSON
   * changeset string, for the bidirectional sync orchestration. `sinceMs`
   * is a millisecond epoch timestamp (the persisted sync cursor).
   */
  exportChanges(sinceMs: number, collections: Array<string>): string
  /**
   * Merge a JSON changeset string (from a remote peer) into the local
   * database via Last-Write-Wins. Returns the number of documents changed.
   */
  importChanges(changesetJson: string): number
  /**
   * Merge a JSON changeset through a tolerant structural validator built from
   * `schemas_json` — a `{ "<collection>": { version, required, types,
   * defaults } }` object. Every imported upsert is normalized, skipped, or
   * quarantined per its collection schema before Last-Write-Wins; a rejected
   * document is set aside (see `quarantined`), never dropped, and never
   * aborts the batch. Returns `{ applied, skipped, quarantined }`.
   */
  importChangesValidated(changesetJson: string, schemasJson: string): JsonValue
  /**
   * Return every document currently held in `collection`'s quarantine table,
   * each as `{ document, reason, changedAt }`. Empty when nothing has been
   * set aside. For operator inspection and recovery tooling.
   */
  quarantined(collection: string): Array<JsonValue>
  /**
   * Read the current application migration version (0 if never set). Backs
   * the `openDB({ migrations })` runner, which advances it per migration.
   */
  userVersion(): number
  /**
   * Persist the application migration version. Called after each migration's
   * body succeeds so a crash mid-run resumes from the last applied version.
   */
  setUserVersion(version: number): void
  /**
   * Get a collection by name. If an HTTP sync hook is configured it is
   * automatically attached to the returned collection.
   */
  collection(name: string): CollectionNode
}
export declare class CollectionNode {
  /** Insert a document. Returns the ULID string id. */
  insert(doc: JsonValue): string
  /** Insert multiple documents. */
  insertMany(docs: Array<JsonValue>): Array<string>
  /** Find documents matching the filter. */
  find(filter: JsonValue): Array<JsonValue>
  /** Find a single document or return null. */
  findOne(filter: JsonValue): JsonValue | null
  /**
   * Run a MongoDB-style aggregation pipeline. `pipeline` is a JSON array of
   * stage objects (`$match`, `$group`, `$sort`, `$skip`, `$limit`,
   * `$project`). Returns the resulting documents.
   */
  aggregate(pipeline: JsonValue): Array<JsonValue>
  /** Update the first matching document. */
  updateOne(filter: JsonValue, update: JsonValue): boolean
  /** Update all matching documents. */
  updateMany(filter: JsonValue, update: JsonValue): number
  /** Delete the first matching document. */
  deleteOne(filter: JsonValue): boolean
  /** Delete all matching documents. */
  deleteMany(filter: JsonValue): number
  /** Count documents matching the filter. */
  count(filter: JsonValue): number
  /** Create a secondary index on a field. */
  createIndex(field: string): void
  /** Drop a secondary index. */
  dropIndex(field: string): void
  /** Create a compound (multi-field) index over an ordered list of fields. */
  createCompoundIndex(fields: Array<string>): void
  /** Drop a compound index by its ordered field list. */
  dropCompoundIndex(fields: Array<string>): void
  /**
   * Create a vector index on `field`.
   *
   * - `metric` — optional: `"cosine"` (default), `"dot"`, or `"euclidean"`.
   * - `index_type` — optional: `"flat"` (default) or `"hnsw"`.
   * - `hnsw_m` — HNSW connectivity (default 16).
   * - `hnsw_ef_construction` — build quality (default 200).
   */
  createVectorIndex(field: string, dimensions: number, metric?: string | undefined | null, indexType?: string | undefined | null, hnswM?: number | undefined | null, hnswEfConstruction?: number | undefined | null): void
  /** Drop a vector index (and its HNSW graph if present). */
  dropVectorIndex(field: string): void
  /**
   * Rebuild the HNSW graph for a vector index from the current flat data.
   * No-op when the feature is disabled or the index is flat-only.
   */
  upgradeVectorIndex(field: string): void
  /**
   * Find the `top_k` nearest documents to `query`.
   *
   * `filter` — optional pre-filter in the same JSON object format as `find`.
   *
   * Returns an array of `{ document: {...}, score: number }` objects.
   */
  findNearest(field: string, query: Array<number>, topK: number, filter?: JsonValue | undefined | null): Array<JsonValue>
  /**
   * Zero-copy Float32Array fast path. Avoids the f64→f32 conversion loop
   * used by `findNearest(number[])`, which matters for large embeddings
   * (768/1024/1536 dims) called on the hot path.
   */
  findNearestF32(field: string, query: Float32Array, topK: number, filter?: JsonValue | undefined | null): Array<JsonValue>
  /**
   * Async variant of `findNearest` — runs on the libuv thread pool so large
   * scans or unfiltered HNSW queries don't block the JS thread. Accepts a
   * `Float32Array` for zero-copy embedding transfer.
   */
  findNearestAsync(field: string, query: Float32Array, topK: number, filter?: JsonValue | undefined | null): Promise<Array<any>>
  /**
   * Async variant of `find` — runs on the libuv thread pool so large
   * collection scans don't block the JS thread.
   */
  findAsync(filter: JsonValue): Promise<Array<any>>
  /**
   * Async variant of `insert` — the write (and any HTTP sync hook retries)
   * runs on the libuv thread pool instead of blocking the JS thread.
   */
  insertAsync(doc: JsonValue): Promise<string>
  /** Async variant of `insertMany`. */
  insertManyAsync(docs: Array<JsonValue>): Promise<Array<string>>
  /** Async variant of `updateOne`. */
  updateOneAsync(filter: JsonValue, update: JsonValue): Promise<boolean>
  /** Async variant of `updateMany`. */
  updateManyAsync(filter: JsonValue, update: JsonValue): Promise<number>
  /** Async variant of `deleteOne`. */
  deleteOneAsync(filter: JsonValue): Promise<boolean>
  /** Async variant of `deleteMany`. */
  deleteManyAsync(filter: JsonValue): Promise<number>
}
